# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        

      # Build package using npm 
      - name: build npm 
        run: | 
         git clone https://github.com/nixvarghese01/coit-simple-micro-GA.git
         cd coit-frontend 
         npm install && npm run build
      
      # Docker Login
      - name: Docker login
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
         DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            
      # Build container image 
      - name: build container image  
        run: | 
         docker build coit-frontend -t nixvarghese03/coit-simple-micro-ga:latest -f coit-frontend/Dockerfile-multistage
     
      # push container image 
      - name: push container image  
        run: | 
         docker push nixvarghese03/coit-simple-micro-ga:latest 
      
